# Generated by Django 3.1 on 2020-09-08 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=datetime.datetime(2020, 9, 8, 21, 48, 14, 847647, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
    ]
